shim-version: v0.2.6@sha256:db5221f8e0c92562ddbe7d708a374ee0ca393bddc49e3ab2add5e23d8052b843
cvm-version: 0.5.6
cpus: 16
memory: 524288
vllm: false

containers:
  - name: "flux"
    image: ""
    args: [
      "--runtime", "nvidia",
      "--gpus", "all",
      "--ipc", "host",
      "-e", "HF_TOKEN=$(awk -F': *' '$1~/^hf-token$/{print $2; exit}' /mnt/ramdisk/external-config.yml)",
      "-e", "MODELS_DOWNLOAD=dev",
      "frefrik/comfyui-flux:cu128"
    ]

shim:
  listen-port: 443
  upstream-port: 8188
  tls-mode: self-signed
  publish-attestation: false
