shim-version: v0.2.6@sha256:db5221f8e0c92562ddbe7d708a374ee0ca393bddc49e3ab2add5e23d8052b843
cvm-version: 0.5.6
cpus: 16
memory: 524288
vllm: false

models:
  - name: "flux1"
    repo: "black-forest-labs/FLUX.1-dev@3de623fc3c33e44ffbe2bad470d0f45bccf2eb21"
    mpk: "6610a816d111e756c75ec3b875fc8192850bd96bc97c48f499bf04d953d446e4_57885954048_5ffa9292-14e4-5aed-8f99-0fd744b8b6c2"

containers:
  - name: "flux"
    image: ""
    args: [
      "--runtime", "nvidia",
      "--gpus", "all",
      "--ipc", "host",
      "-e", "HF_TOKEN=$(awk -F': *' '$1~/^hf-token$/{print $2; exit}' /mnt/ramdisk/external-config.yml)",
      "-e", "MODELS_DOWNLOAD=dev",
      "frefrik/comfyui-flux:cu128"
    ]

shim:
  listen-port: 443
  upstream-port: 8188
  tls-mode: self-signed
  publish-attestation: false
